<?php

namespace Test\App\database;

use App\database\OHLCVFromDatabase;
use App\models\TimeFrame;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-03 at 21:03:15.
 */
class OHLCVFromDatabaseTest extends TestCase {

    /**
     * @var OHLCVFromDatabase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new OHLCVFromDatabase("SOL/USDT", new TimeFrame("30m"));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {

    }

    /**
     * @covers App\database\OHLCVFromDatabase::saveOHLCV
     * @todo   Implement testSaveOHLCV().
     */
    public function testSaveOHLCV() {
//        $thi->assertEquals('', $this->object->SaveOHLCV());;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers App\database\OHLCVFromDatabase::queryDatabase
     * @todo   Implement testQueryDatabase().
     */
    public function testQueryDatabase() {
//        $this->assertEqual('', $this->object->QueryDatabase());;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
