<?php

namespace Test\App\models;

use App\models\OHLCV;
use App\models\OHLCVCollection;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-01 at 04:40:59.
 */
class OHLCVCollectionTest extends TestCase {

    /**
     * @var OHLCVCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new OHLCVCollection();

        $ohcl1 = [
            1504541580000, // UTC timestamp in milliseconds, integer
            4230.4, // (O)pen price, float
            4240.8, // (H)ighest price, float
            4230.0, // (L)owest price, float
            4230.7, // (C)losing price, float
            35.000001    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];

        $ohcl2 = [
            1504541680000, // UTC timestamp in milliseconds, integer
            4231.4, // (O)pen price, float
            4241.8, // (H)ighest price, float
            4231.0, // (L)owest price, float
            4231.7, // (C)losing price, float
            35.000002   // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $ohcl3 = [
            1504541880000, // UTC timestamp in milliseconds, integer
            4233.4, // (O)pen price, float
            4243.8, // (H)ighest price, float
            4233.0, // (L)owest price, float
            4233.7, // (C)losing price, float
            37.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $ohcl4 = [
            1504541980000, // UTC timestamp in milliseconds, integer
            4234.4, // (O)pen price, float
            4244.8, // (H)ighest price, float
            4234.0, // (L)owest price, float
            4234.7, // (C)losing price, float
            38.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];

        $this->object->add(new OHLCV($ohcl1));
        $this->object->add(new OHLCV($ohcl2));
        $this->object->add(new OHLCV($ohcl3));
        $this->object->add(new OHLCV($ohcl4));
    }

    /**
     * @covers App\models\OHLCVCollection::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $ohcl5 = [
            1504541980000, // UTC timestamp in milliseconds, integer
            4234.4, // (O)pen price, float
            4244.8, // (H)ighest price, float
            4234.0, // (L)owest price, float
            4234.7, // (C)losing price, float
            38.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $this->object->Add(new OHLCV($ohcl5));
        $this->assertEquals(5, $this->object->getCount());
    }

    /**
     * @covers App\models\OHLCVCollection::getCount
     * @todo   Implement testGetCount().
     */
    public function testGetCount() {
        $this->assertEquals(4, $this->object->GetCount());
    }

}
