<?php

namespace Test\App\models;

use App\models\OHLCV;
use App\models\OHLCVCollection;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-01 at 04:40:59.
 */
class OHLCVCollectionTest extends TestCase {

    /**
     * @var OHLCVCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new OHLCVCollection();

        $ohcl0 = [
            1504541580000, // UTC timestamp in milliseconds, integer
            4230.4, // (O)pen price, float
            4240.8, // (H)ighest price, float
            4230.0, // (L)owest price, float
            4230.7, // (C)losing price, float
            35.000001    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];

        $ohcl1 = [
            1504541680000, // UTC timestamp in milliseconds, integer
            4231.4, // (O)pen price, float
            4241.8, // (H)ighest price, float
            4231.0, // (L)owest price, float
            4231.7, // (C)losing price, float
            35.000002   // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $ohcl2 = [
            1504541780000, // UTC timestamp in milliseconds, integer
            4232.4, // (O)pen price, float
            4242.8, // (H)ighest price, float
            4232.0, // (L)owest price, float
            4232.7, // (C)losing price, float
            37.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $ohcl3 = [
            1504541880000, // UTC timestamp in milliseconds, integer
            4233.4, // (O)pen price, float
            4243.8, // (H)ighest price, float
            4233.0, // (L)owest price, float
            4233.7, // (C)losing price, float
            38.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];

        $this->object->add(new OHLCV($ohcl0));
        $this->object->add(new OHLCV($ohcl1));
        $this->object->add(new OHLCV($ohcl2));
        $this->object->add(new OHLCV($ohcl3));
    }

    /**
     * @covers App\models\OHLCVCollection::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $ohcl4 = [
            1504541980000, // UTC timestamp in milliseconds, integer
            4234.4, // (O)pen price, float
            4244.8, // (H)ighest price, float
            4234.0, // (L)owest price, float
            4234.7, // (C)losing price, float
            38.000003    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $this->object->Add(new OHLCV($ohcl4));
        $this->assertEquals(5, $this->object->getCount());
    }

    /**
     * @covers App\models\OHLCVCollection::getCount
     * @todo   Implement testGetCount().
     */
    public function testGetCount() {
        $this->assertEquals(4, $this->object->GetCount());
    }

    public function testGetCloses() {
        $closes = [4230.7, 4231.7, 4232.7, 4233.7];
        $this->assertEquals($closes, $this->object->getCloses());
    }

    public function testGetOpens() {
        $opens = [4230.4, 4231.4, 4232.4, 4233.4];
        $this->assertEquals($opens, $this->object->getOpens());
    }

    public function testGetHighs() {
        $highs = [4240.8, 4241.8, 4242.8, 4243.8];
        $this->assertEquals($highs, $this->object->getHighs());
    }

    public function testGetLows() {
        $lows = [4230.0, 4231.0, 4232.0, 4233.0];
        $this->assertEquals($lows, $this->object->getLows());
    }

    public function testGetTimeStamps() {
        $timeStamps = [1504541580000, 1504541680000, 1504541780000, 1504541880000];
        $this->assertEquals($timeStamps, $this->object->getTimestamps());
    }

    public function testGetSpecificOpen() {
        $this->assertEquals(4233.4, $this->object->getOpens(3));
    }

    public function testGetSpecificClose() {
        $this->assertEquals(4232.7, $this->object->getCloses(2));
    }

    public function getHighs() {
        $this->assertEquals(4241.8, $this->object->getHighs(1));
    }

    public function testGetSpecificLow() {
        $this->assertEquals(4230.0, $this->object->getLows(0));
    }

    public function testGetSpecificTimestamp() {
        $this->assertEquals(1504541880000, $this->object->getTimestamps(3));
    }

    public function testSpecitTimeStampFormat() {
        $this->assertEquals("2017-09-04 16:18:00", $this->object->getFormatedTimeStamp(3));
    }

}
