<?php

namespace Test\App\models;

use App\models\OHLCV;
use App\models\OHLCVCollection;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-01 at 03:30:09.
 */
class OHLCVCollectionTest extends TestCase {

    public function testAddOHLC() {
        $ohcl       = [
            1504541580000, // UTC timestamp in milliseconds, integer
            4235.4, // (O)pen price, float
            4240.6, // (H)ighest price, float
            4230.0, // (L)owest price, float
            4230.7, // (C)losing price, float
            37.72941911    // (V)olume float (usually in terms of the base currency, the exchanges docstring may list whether quote or base units are used)
        ];
        $collection = new OHLCVCollection();
        $collection->add(new OHLCV($ohcl));
        $this->assertEquals(1, $collection->getCount());
        $collection->add(new OHLCV($ohcl));
        $this->assertEquals(2, $collection->getCount());
        $collection->add(new OHLCV($ohcl));
        $this->assertEquals(3, $collection->getCount());
        $collection->add(new OHLCV($ohcl));
        $this->assertEquals(4, $collection->getCount());
    }

}
