<?php

namespace Test\App\extensions;

use App\extensions\BotException;
use App\extensions\BotExchange;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-01 at 18:49:42.
 */
class ExchangeTest extends TestCase {

    public function testBinanceAsValidExchange() {
        $exchange = new BotExchange("binance");
        $this->assertEquals("ccxt\\binance", get_class($exchange->getExchange()));
    }

    public function testKrakenAsValidExchange() {
        $exchange = new BotExchange("kraken");
        $this->assertEquals("ccxt\\kraken", get_class($exchange->getExchange()));
    }

    public function testInvalidExchante() {
        $this->expectException(BotException::class);
        new BotExchange("inexistent");
    }

    public function testDefaultExchange() {
        $_ENV["EXCHANGE"] = "binance";
        $exchange         = new BotExchange();
        $this->assertEquals("ccxt\\binance", get_class($exchange->getExchange()));
    }

}
