<?php

namespace Test\App\extensions;

use App\extensions\FetchOHLCV;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-09-04 at 06:14:11.
 */

/**
 * @runTestsInSeparateProcesses
 */
class FetchOHLCVTest extends \PHPUnit\Framework\TestCase {

    public function testSinceDateExchange() {

        $exchange = new FetchOHLCV();
        $data     = $exchange->fetchOHLCV("SOL/USDT", new \App\models\TimeFrame("30m"), new \DateTime("2020-12-31 00:00:00"), limit: 2);
        $this->assertEquals("2020-12-31 00:00:00", $data->getFormatedTimeStamp(0));
        $this->assertEquals(2, $data->getCount());
    }

    public function testDates() {
        $exchange = new FetchOHLCV();
        $date     = new \DateTime("now");
        $data     = $exchange->fetchOHLCV("SOL/USDT", new \App\models\TimeFrame("1d"));
        $this->assertEquals($date->format("Y-m-d 00:00:00"), $data->getFormatedTimeStamp(499));
        $date->sub(\DateInterval::createFromDateString("499 days"));
        $this->assertEquals($date->format("Y-m-d 00:00:00"), $data->getFormatedTimeStamp(0));
        $this->assertEquals(500, $data->getCount());
    }

}
